### PR TITLE
SEAT-70 Created a map legend

### PR DESCRIPTION
**Pull request by mayavera**
## Changelog
- installed `reselect` to handle memoizing derived calculations
- installed `node-sass`, `sass-loader` to compile sass files to css
- installed `@fontawesome/*` to display pretty icons
- installed `classnames` to handle combining classes and conditionally setting classes on components
- installed `normalize-scss` to reset default html styles (only used in `./examples/using-module`)
- created `Legend` component

## Testing Instructions
1. `yarn start`
1. wait for your browser to open the example page
1. you should now see a box in the top right corner of the page
1. there should be text in the box that should read "Show Map Legend"
1. there should be a down arrow to the left of the text
1. click the box
1. the box should have expanded to show multiple options
1. "Show Map Legend" should now read "Hide Map Legend"
1. the down arrow should now be an up arrow
1. there should be a small colored square for each option
1. there should be a cost range for each option
1. the costs should be displayed in rounded dollar amounts
1. none of the costs for the option should overlap
1. click the "Hide Map Legend" box
1. the options should now be hidden
1. "Hide Map Legend" should now read "Show Map Legend
1. the down arrow should now be an up arrow
1. ㊗️ 🎊 🐠 

## Jira Tickets
[SEAT-70](https://ticketevolution.atlassian.net/browse/SEAT-70)

### CODE REVIEW

**Comment by josephspens** [comment]
My main concern with this PR is its introduction of a bunch of tools that we don't currently use at Tevo. I'm not against introducing new tools but we should decide as a team to admit/disallow them.

In addition to `sass` I don't see the need for `classnames`, `reselect`, and `postcss`. From what I can tell `classnames` is a node package that does the same thing as string interpolation. Webpack is able to autoprefix CSS rules for us, which seems to be what we would be using `postcss` for.

It seems reselect was used as a means to simplify the percentile logic. An alternative solution, which requires no additional tooling, also has the benefit of not duplicating the percentile logic between `costRanges` and `getDefaultColor`.

```javascript
mostExpensiveTicketGroupPriceForPercentile (percentile) => {
    const indexOfMostExpensiveTicketGroupPrice = Math.floor(this.sortedTicketGroupPrices.length * percentile)
    return this.sortedTicketGroupPrices[indexOfMostExpensiveTicketGroupPrice]
}

leastExpensiveTicketGroupPriceForPercentile (percentile) => {
    const sectionPercentiles = Object.keys(this.props.sectionPercentiles).sort((a, b) => a - b)
    const previousPercentile = sectionPercentiles[sectionPercentiles.indexOf(percentile) - 1]
    if (!previousPercentile) {
        return 0
    }
    const indexOfLeastExpensiveTicketGroupPrice = Math.ceil(this.sortedTicketGroupPrices.length * previousPercentile) + 1
    return this.sortedTicketGroupPrices[indexOfLeastExpensiveTicketGroupPrice]
}

costRanges () => Object.entries(this.props.sectionPercentiles)
    .sort(([percentileA], [percentileB]) => percentileA - percentileB)
    .map((memo, [percentile, color]) => ({
        color,
        minPrice: this.leastExpensiveTicketGroupPriceForPercentile(percentile),
        maxPrice: this.mostExpensiveTicketGroupPriceForPercentile(percentile)
    }))

getDefaultColor (ticketGroups) {
    const lowestTicketPriceInSection = ticketGroups.map(({ price }) => price).sort((a, b) => a - b)[0]
    for (const costRange of this.costRanges()) {
        if (lowestTicketPriceInSection <= costRange.maxPrice) {
            return costRange.color
        }
    }
}
```

**Comment by jwcobb** [comment]
> It seems reselect was used as a means to simplify the percentile logic. An alternative solution, which requires no additional tooling, also has the benefit of not duplicating the percentile logic between `costRanges` and `getDefaultColor`.

I am under the impression that the long term strategy is to color sections by zone like every other seating chart provider and not by price, but that we currently have some limitations preventing us from doing that. 

Please confirm this long term plan with Cole, but figured I would point that out in case it was worth factoring in to a decision around usage of `reselect`.

**Comment by bbaisley** [comment]
Can we get a discussion going on this? Sass is modifying our tech stack and should be discussed. I'm also concerned (download size) about requiring something like fontawesome in a lib for embedding in other sites.

**Comment by mayavera** [comment]
Due to tree-shaking, using `font-awesome` is leaner than it might seem (we’re only bundling the icons we reference). If you’re worried about the overhead of `<FontAwesomeIcon>` (~400 lines) we could download the icon `svg` and render it directly (we’re already bundling our `svg`s as `base64-data-urls`).

As for using `sass`, I originally attempted to complete this feature using component styles (in line with the rest of this project), but I found it difficult to read and manage. After speaking with @josephspens, we agree that pulling in `sass` isn't the right solution for this project. Refactoring this project's styles to use `styled-component` seems like the best approach, but it's outside the scope of this feature. In the meantime, I'm going to re-write this feature's feature's styles using component styles and remove `sass` and `sass-loader`.

**Comment by mayavera** [comment]
Please refer to #84 for a continuation of this conversation and feature development

**Pull request closed without merging**
